# Generated by Django 4.2.1 on 2023-05-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_exchangerateprovider_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='date',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
